# Generated by Django 5.1.1 on 2026-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('location', models.CharField(max_length=25)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
