# Generated by Django 5.1.1 on 2026-05-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcontent',
            name='company',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='appcontent',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('r1', 'Round 1'), ('r2', 'Round 2'), ('r3', 'Round 3'), ('r4', 'Round 4'), ('final', 'Final Round'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
