# Generated by Django 5.1.1 on 2026-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTasks', '0002_appcontent_company_appcontent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcontent',
            name='company',
            field=models.CharField(default='', max_length=20),
        ),
    ]
